### ISSUE TITLE
Error when using the redportal command

### ISSUE THREAD

**Issue by LazyHatGuy** [orels1/Red-Portal-Cogs#5]
Every time I try to use the redportal command I get the following error
```
Ignoring exception in command redportal
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/tlhg/ShitPost/RPC/redportal/redportal.py", line 25, in redportal
    await self.bot.send_cmd_help(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'send_cmd_help'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 630, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'send_cmd_help'
```

**Comment by LazyHatGuy** [comment]
I also tried to install a cog using the command :
`sp;cog install Dusty-Cogs desutils`
And received the error :
`Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "cog" is not found`

**Comment by LazyHatGuy** [comment]
Never mind. I needed to use Red as a base
